pipeline { 
    agent any
    tools {
        maven 'mvn'
    }
    stages {
        stage('Build') { 
            steps { 
                dir("SampleCode/JPrint/"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test') { 
            steps { 
                echo "Building $JOB_NAME" 
            }
        }
        
    }
}
