apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pysureset
spec:
  revisionHistoryLimit: 4
  replicas: 4
  selector:
    matchLabels:
      app: pyapp
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: brokenleg/pyapp:1.3
        ports:
        - containerPort: 8000