def PATH_TO_SCRIPT="SampleCode/java-http"

pipeline { 
    agent any
    options {
        timestamps()
    }
    stages {
        stage ('Checkout'){
            steps {
                git branch: "main",
                credentialsId: "github",
                url: "https://github.com/codehub-learn/containers-internal-showcase.git"
                }
        }
        stage('Build') { 
            steps { 
                dir("${PATH_TO_SCRIPT}"){
                    sh 'shellprint.sh'
                }
            }
        }
        stage('Unit Testing') { 
            steps { 
                dir("${PATH_TO_SCRIPT}"){
                    sh 'echo "Unit Testing complete"'
                }
            }
       }
/*        stage('Package') { 
            steps { 
                dir("${PATH_TO_SCRIPT}"){
                    sh 'mvn package -Dmaven.test.skip=true'
                }
            }
            post {
                success{
                    archiveArtifacts artifacts: "**/target/*.jar"
                }               
            }
        }
         stage ('Create docker Image') {
            steps {
                dir("${PATH_TO_SCRIPT}"){
                    script{
                        dockerImage = docker.build imagename
                    }
                }
            }
        }
        stage('Publish image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Deploy Image in container') {
            steps{
                    script{
                        docker.image(imagename).run('-d -p 8900:8900 --name jprint --network jenkins')
                    }
                }
            }
        stage('Run Integrations tests') {
            steps{
                script{
                    sh "curl -v http://jprint:8900 "
                }
            }
        }
        stage('Release image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        dockerImage.push('STABLE')
                        dockerImage.push("RELEASE-$BUILD_NUMBER")
                    }
                }
            }
        }
 
        
    }
    post {
            failure {
                mail to: "kmakedos@athtech.gr",
                subject: "Build Failed: $BUILD_TAG",
                body: "Link to JOB $BUILD_URL"
            }
        }
    }
    */
    }
}
