apiVersion: v1
kind: Service
metadata: 
  name: pyservice
  namespace: pyhub
spec:
  selector:
    app: webs 
    env: dev
  ports:
    - name: nginx
      protocol: TCP
      port: 9080
      targetPort: 80
    - name: webport
      protocol: TCP
      port: 9000
      targetPort: 8000
  type: LoadBalancer
