apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapp
  name: simpleapp-deploy
  namespace: app
spec:
  replicas: 100
  selector:
    matchLabels:
      app: simpleapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - image: brokenleg/simpleapp:3.0
        name: simpleapp
        resources: {}
        env:
          - name: REDIS_HOST
            value: cache.cache.svc.cluster.local
