apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: snm-app
  labels:
    name: app
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    name: app
  type: LoadBalancer
