apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simpleapp-ds
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simpleapp
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: simpleapp
        image: brokenleg/simpleapp:2.0
        env:
          - name: REDIS_HOST
            value: localhost
      - name: redis
        image: redis:alpine

