---
- name: Setup Apache in Debian
  hosts: debian_servers
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: latest
      become: true

    - name: Start Apache
      ansible.builtin.command:
        cmd: apache2ctl start
      become: true

