apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: main
    image: busybox:latest
    command: ["sh", "-c", "echo The app is running! && sleep 3600"]
  initContainers:
  - name: init-main
    image: busybox:latest
    command: ["sh", "-c", "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2 ; done"]
  - name: init-db
    image: busybox:latest
    command: ["sh", "-c", "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb ; sleep 2 ; done "]

