---
- name: Hello world
  hosts: all
  vars:
    message: "Gello"
  tasks:
    - name: Say hi to people
      debug:
        msg: "{{ message }}"


- name: Hello world again
  hosts: debian_servers
  tasks:
    - name: Give an inspiring message
      debug:
        msg: "{{ message2 }}"


- name: Register a var
  hosts: debian_servers
  tasks:  
    - name: Register
      ansible.builtin.shell: /bin/ls /
      register: ls_result

    - name: Print ls output
      debug:  
        msg: "{{ ls_result.stdout }}"