apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: single.littledevel.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: single
            port:
              number: 8900
