apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
  labels:
    env: dev
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webs
      env: dev
  template:
    metadata:
      labels:
        app: webs
        env: dev
    spec:
      containers:
        - name: pyapp
          image: brokenleg/pyapp:1.3
          ports:
          - containerPort: 8000
