apiVersion: v1
kind: Service
metadata: 
  name: pyapp-cluster
spec:
  selector:
    app: webs 
    env: dev
  ports:
    - name: webport
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
