apiVersion: v1
kind: Service
metadata: 
  name: webcluster
spec:
  selector:
    app: webs 
    env: dev
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: webport
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
