apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
  labels:
    env: dev
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webs
      env: dev
  template:
    metadata:
      labels:
        app: webs
        env: dev
    spec:
      containers:
        - name: alpha
          image: nginx
          ports:
            - containerPort: 8080
        - name: beta
          image: brokenleg/serverapp:1.2
          ports:
            - containerPort: 8000
