pipeline { 
    agent any
    tools {
        maven 'mvn'
    }
    options {
        timestamps()
    }
    environment {
        imagename = "brokenleg/jprint"
        dockercredentials = 'dockerhub'
        dockerImage = ''
    }

    stages {
        stage ('Checkout'){
            steps {
                git branch: "main",
                credentialsId: "github",
                url: "https://github.com/codehub-learn/containers-internal-showcase.git"
                }
        }
        stage('Build') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Testing') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn clean test'
                }
            }
            post {
                failure{
                    archiveArtifacts artifacts: "**/target/surefire-reports/*.xml"
                }
            }
        }
        stage('Package') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn package -Dmaven.test.skip=true'
                }
            }
            post {
                success{
                    archiveArtifacts artifacts: "**/target/*.jar"
                }               
            }
        }
         stage ('Create docker Image') {
            steps {
                dir("java-http/"){
                        sh "echo creating docker image $imagename"
                }
            }
        }
        stage('Publish image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Deploy Image in container') {
            steps{
                    script{
                        docker.image(imagename).run('-d -p 8900:8900 --name jprint --network jenkins')
                    }
                }
            }
        stage('Run Integrations tests') {
            steps{
                script{
                    sh "curl -v http://jprint:8900 "
                }
            }
        }
        stage('Release image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        dockerImage.push('STABLE')
                        dockerImage.push("RELEASE-$BUILD_NUMBER")
                    }
                }
            }
        }
 
    }
        
    post {
        failure {
            mail to: "kmakedos@athtech.gr",
            subject: "Build Failed: $BUILD_TAG",
            body: "Link to JOB $BUILD_URL"

        }
        always{
            junit "**/target/surefire-reports/*.xml"
            script {
                try{
                    sh "docker container stop jprint"
                    sh "docker container rm jprint"
                }catch (err) {
                    echo "Deleting container failed..."
                }
            }
        }
    }
}
