pipeline { 
    agent any
    tools {
        maven 'mvn'
    }
    options {
        timestamps()
    }
    environment {
        imagename = "brokenleg/jprint"
        dockercredentials = 'dockerhub'
        dockerImage = ''
    }

    stages {
        stage ('Checkout'){
            steps {
                git branch: "main",
                credentialsId: "github",
                url: "https://github.com/codehub-learn/containers-internal-showcase.git"
                }
        }
        stage('Build') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Testing') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn clean test'
                }
            }
            post {
                failure{
                    archiveArtifacts artifacts: "**/target/surefire-reports/*.xml"
                }
            }
        }
        stage('Package') { 
            steps { 
                dir("java-http/"){
                    sh 'mvn package -Dmaven.test.skip=true'
                }
            }
            post {
                success{
                    archiveArtifacts artifacts: "**/target/*.jar"
                }               
            }
        }
         stage ('Create docker Image') {
            steps {
                dir("java-http/"){
                    sh "echo creating docker image $imagename"
                }
            }
         }
        stage('Publish image to registry') {
            steps{
                    sh "echo Publishing docker image to registry"
                }
            }
        stage('Deploy Image in container') {
            steps{
                    sh "echo Deploy to testing env"
                }
            }
        stage('Run Integrations tests') {
            steps{
                    sh "echo Running integration tests "
            }
        }
        when { tag "release-*" }`
        stage('Release image to registry') {
            steps{
                    sh "echo Releasing image"
                }
            }
        }
 
        
    post {
        failure {
            mail to: "kmakedos@athtech.gr",
            subject: "Build Failed: $BUILD_TAG",
            body: "Link to JOB $BUILD_URL"

        }
        always{
            junit "**/target/surefire-reports/*.xml"
            script {
                try{
                    sh "docker container stop jprint"
                    sh "docker container rm jprint"
                }catch (err) {
                    echo "Deleting container failed..."
                }
            }
        }
    }
}
