---
- name: Setup environment
  hosts: all
  tasks: 
  - name: Add Groups
    group:
      name: "{{ item }}"
    with_items: "{{ www_user }}"
    become: true

  - name: Add Users
    user:
      name: "{{ item }}"
      group: "{{ item }}"
      shell: "/bin/bash"
    with_items: "{{ www_user }}"
    become: true

  - name: Create Folders 
    file:
      path: "{{ item }}"
      owner: "{{ www_user }}"
      group: "{{ www_user }}"
      state: directory
      recurse: true
    with_items: "{{ folder_list }}"
    become: true

- name: Setup Apache in Debian
  hosts: debian_servers
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: latest
      become: true
    - name: Start Apache
      ansible.builtin.command:
        cmd: apache2ctl start
      become: true

- name: Setup Nginx in Fedora
  hosts: fedora_servers
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest
      become: true

    - name: Check Nginx Status 
      stat:
        path: /run/nginx.pid
      register: nginx_pid_status

    - name: Start Nginx
      ansible.builtin.command:
        cmd: nginx
      become: true
      when: not nginx_pid_status.stat.exists

