apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
spec:
  replicas: 9
  selector:
    matchLabels:
      app: webs
      env: dev
  template:
    metadata:
      labels:
        app: webs
        env: dev
    spec:
      containers:
        - name: alpha
          image: nginx
          ports:
            - containerPort: 80
        - name: beta
          image: brokenleg/serverapp:1.2
          ports:
            - containerPort: 8000

    
