apiVersion: batch/v1
kind: Job
metadata:
  name: pyjob
spec:
  backoffLimit: 6
  completions: 2
  parallelism: 2
  template:
    spec:
      containers:
      - name: hello
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["echo hello from $HOSTNAME!"]
      restartPolicy: Never

