- name: Install Apache
  package:
    name: apache2
    state: latest
  become: true

- name: Start Apache
  ansible.builtin.command:
    cmd: apache2ctl start
  become: true

- name: Copy index.html
  copy:
    src: "{{ index_file }}"
    dest: "{{ index_file_dest }}/index.html"
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
  become: true


- name: Template index.html
  template:
    src: "{{ index_file }}.j2"
    dest: "{{ index_file_dest }}/index.html"
    owner: "{{ www_user }}"
    group: "{{ www_user }}"
  become: true

