def PATH_TO_POM="SampleCode/java-http"

pipeline { 
    agent {
        label 'docker'
    }
    tools {
        maven 'mvn'
    }
    options {
        timestamps()
    }
    environment {
        imagename = "brokenleg/jprint"
        dockercredentials = 'dockerhub'
        dockerImage = ''
    }
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'dev', description: 'Docker image tag') 
        string(name: 'RELEASE_TAG', defaultValue: 'release', description: 'Docker image tag') 
    }
 
    stages {
        stage('Deploy Image in container') {
            steps{
                    script{
                        docker.image("${imagename}:${params.IMAGE_TAG}").run('-d -p 8900:8900 --name jprint --network jenkins')
                    }
                }
            }
        stage('Run Integrations tests') {
            steps{
                script{
                    sh "curl -v http://jprint:8900 "
                }
            }
        }
        stage('Release image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        docker.image("${imagename}:${params.RELEASE_TAG}").push("${params.RELEASE_TAG}")
                    }
                }
            }
        }
 
    }
        
    post {
        failure {
            mail to: "kmakedos@athtech.gr",
            subject: "Build Failed: $BUILD_TAG",
            body: "Link to JOB $BUILD_URL"

        }
        always{
            script {
                try{
                    sh "docker container stop jprint"
                    sh "docker container rm jprint"
                }catch (err) {
                    echo "Deleting container failed..."
                }
            }
        }
    }
}
