# A example scrape configuration for running Prometheus with Docker.

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    basic_auth:
      username: "admin"
      password: "codehub"
    static_configs:
      - targets: ["jenkins:8080"]

