apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simpleapp
  name: simpleapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 4
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - image: brokenleg/simpleapp:3.0
        name: simpleapp
        resources: {}
        env:
          - name: REDIS_HOST
            value: localhost
      - image: redis:alpine
        name: redis
        resources: {}
