apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  labels:
    name: db
    app.kubernetes.io/name: db
data:
  primary.cnf: |
    [mysqld]
    log-bin
    bind-address=0.0.0.0
  replica.cnf: |
    [mysqld]
    super-read-only
