apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: snm-db
  annotations: 
  labels:
    name: db
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      name: db
  strategy: 
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        name: db
    spec:
      containers:
        - name: db
          image: docker.io/brokenleg/db:1.0
          ports:
            - containerPort: 3306
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      restartPolicy: Always

