apiVersion: v1
kind: Service
metadata:
  name: db-ro
  namespace: snm-db
  labels:
    app: db
    app.kubernetes.io/name: db
    readonly: "true"
spec:
  ports:
    - name: mysql
      port: 3306
  clusterIP: None
  selector:
    app: db

