apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: snm-db
spec:
  selector:
    matchLabels:
      app: db
      app.kubernetes.io/name: db
  serviceName: db
  replicas: 7
  template:
    metadata:
      labels:
        app: db
        app.kubernetes.io/name: db
    spec:
      initContainers:
        - name: init-mysql
          image: docker.io/brokenleg/db:1.0
          command:
          - bash
          - "-c"
          - |
            set -ex
            [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
            ordinal=${BASH_REMATCH[1]}
            echo [mysqld] > /mnt/conf.d/server-id.cnf
            echo server-id=$((100 + $ordinal )) >> /mnt/conf.d/server-id.cnf
            if [[ $ordinal -eq 0 ]]; then
              cp /mnt/config-map/primary.cnf /mnt/conf.d/
            else
              cp /mnt/config-map/replica.cnf /mnt/conf.d/
            fi
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
            - name: config-map
              mountPath: /mnt/config-map
      containers:
        - name: mysql
          image: docker.io/brokenleg/db:1.0
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: conf
              mountPath: /etc/mysql/conf.d
        - name: nginx
          image: nginx

      volumes:
        - name: conf
          emptyDir: {}
        - name: config-map
          configMap:
            name: db-cm
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
