version: "3.2"
services:

  frontend:
    image: nginx
    ports:
    - "80:80"
    networks:
      - frontend
  app:
    image: brokenleg/app:2.0
    ports:
      - "6000:6000"
    environment:
      - DB_HOST=db
      - DB_USER=snm
      - DB_PASSWORD=snm1234
      - DB_NAME=snm
      - APP_PORT=6000
      - APP_HOSTNAME=0.0.0.0
    networks:
      - frontend
      - backend

  db: 
    image: brokenleg/db:1.0
    networks:
      - backend

networks:
  frontend:
  backend: 
