apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-mypool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.56.150-192.168.56.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-mypool
