def PATH_TO_POM="SampleCode/java-http"

pipeline { 
    agent {
        label 'docker'
    }
    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag') 
    }
    tools {
        maven 'mvn'
    }
    options {
        timestamps()
    }
    environment {
        imagename = "brokenleg/jprint"
        dockercredentials = 'dockerhub'
        dockerImage = "${IMAGE_TAG}"

    }

    stages {
        stage ('Checkout'){
            steps {
                git branch: "jenkins",
                credentialsId: "github",
                url: "https://github.com/codehub-learn/containers-internal-showcase.git"
                }
        }
        stage('Build') { 
            steps { 
                dir("${PATH_TO_POM}"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Testing') { 
            steps { 
                dir("${PATH_TO_POM}"){
                    sh 'mvn clean test'
                }
            }
            post {
                failure{
                    archiveArtifacts artifacts: "**/target/surefire-reports/*.xml"
                }
            }
        }
        stage('Package') { 
            steps { 
                dir("${PATH_TO_POM}"){
                    sh 'mvn package -Dmaven.test.skip=true'
                }
            }
            post {
                success{
                    archiveArtifacts artifacts: "**/target/*.jar"
                }               
            }
        }
         stage ('Create docker Image') {
            steps {
                dir("${PATH_TO_POM}"){
                    script{
                        dockerImage = docker.build imagename
                    }
                }
            }
        }
        stage('Publish image to registry') {
            steps{
                script {
                    docker.withRegistry( '', dockercredentials ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }

    }
        
    post {
        failure {
            mail to: "kmakedos@athtech.gr",
            subject: "Build Failed: $BUILD_TAG",
            body: "Link to JOB $BUILD_URL"

        }
        always{
            junit "**/target/surefire-reports/*.xml"
            script {
                try{
                    sh "docker container stop jprint"
                    sh "docker container rm jprint"
                }catch (err) {
                    echo "Deleting container failed..."
                }
            }
        }
    }
}
